# Generated by Django 2.2.10 on 2020-06-01 10:44

from django.db import migrations
from django.db.models.expressions import RawSQL


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0010_enable'),
    ]

    operations = [
    ]
