---
language: python
os: linux
dist: xenial

python:
  - "3.6"

env:
  - TOXENV=pytest
  - TOXENV=flake8
  - TOXENV=pyright

install:
  - npm install -g pyright@1.1.74
  - pip install -r dev-requirements.txt

script:
  - tox
