---
language: python
os: linux
dist: focal

jobs:
  - language: node_js
    node_js: lts/*
    env: TOXENV=pyright
    install: npm install -g pyright@1.1.74
    script: pyright common_migration
  - python: "3.10"
    env: TOXENV=pytest
  - python: "3.10"
    env: TOXENV=flake8
  - python: "3.9"
    env: TOXENV=pytest
  - python: "3.9"
    env: TOXENV=flake8

install:
  - pip install -r dev-requirements.txt

script:
  - tox
