# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-24 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sites', '0002_alter_domain_unique'),
        ('sites', '0001_initial'),
    ]

    operations = []
