# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-29 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0002_add_ideacopy'),
    ]

    operations = [
    ]
