# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-26 13:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0004_hide'),
    ]

    operations = [
    ]
