# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-26 11:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0005_add_dmaic_fields'),
    ]

    operations = [
    ]
