# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-22 10:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0005_add_separate'),
    ]

    operations = [
    ]
