# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-15 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0006_copy_pas'),
    ]

    operations = [
    ]
