# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-26 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0007_merge'),
    ]

    operations = [
    ]
