# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-15 17:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0007_added'),
    ]

    operations = [
    ]
