# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-30 08:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0008_change'),
    ]

    operations = [
    ]
