# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 15:36
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_squashed'),
    ]

    operations = [
    ]
