# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-17 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0006_client_repository_images'),
    ]

    operations = [
    ]
