# Generated by Django 2.2.5 on 2019-09-20 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0007_client_features'),
    ]

    operations = [
    ]
