# Generated by Django 2.2.5 on 2019-09-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0008_rename'),
    ]

    operations = [
    ]
