# Generated by Django 2.2.10 on 2020-03-01 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0010_enable'),
    ]

    operations = [
    ]
