# Generated by Django 2.2.10 on 2020-04-15 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0011_client_max'),
    ]

    operations = [
    ]
