# Generated by Django 2.2.10 on 2020-05-04 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0011_password'),
    ]

    operations = [
    ]
