# Generated by Django 2.2.11 on 2020-05-21 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0012_challenge'),
        ('tenancy', '0011_password'),
    ]

    operations = [
    ]
