# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-15 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0002_client_site'),
    ]

    operations = [
    ]
