# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-20 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0003_client_session'),
    ]

    operations = [
    ]
