# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-18 10:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0005_client_moderation'),
    ]

    operations = [
    ]
