# Generated by Django 2.2.7 on 2019-11-27 14:05
#
# This script adds the default MOVE_IDEAS feature flag to all sites that
# already exist.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0009_add'),
    ]

    operations = [
    ]
