# Generated by Django 2.2.9 on 2020-02-19 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0010_enable'),
    ]

    operations = [
    ]
